version: "3.8"
services: 
  frontend:
    container_name: frontend
    build: ./hotel-room-booking-app-frontend
    env_file:
      - ./hotel-room-booking-app-frontend/.env
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  backend:
    container_name: backend
    build: ./hotel-room-booking-app-backend
    env_file:
      - ./hotel-room-booking-app-backend/.env
    ports:
      - "5000:5000"
volumes:
  mongo_data:
