version: "3.8"
services: 
  frontend:
    container_name: frontend
    build: ./hotel-room-booking-app-frontend
    env_file:
      - ./hotel-room-booking-app-frontend/.env
    ports:
      - "3000:3000"
    depends_on:  # Fixed `depend_on`
      - backend
    networks:
      - mynetwork

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always  # Ensures MongoDB restarts if it crashes
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork
      
  backend:
    container_name: backend
    build: ./hotel-room-booking-app-backend
    env_file:
      - ./hotel-room-booking-app-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridg      
volumes:
  mongo_data:
